apiVersion: v1
kind: Service
metadata:
  name: public-api
  namespace: {{ .Values.namespace }}
  labels:
    service: public-api
spec:
  selector:
    service: public-api
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
    protocol: TCP
