image:
  app:
    url: 465700395685.dkr.ecr.eu-west-1.amazonaws.com/zilkroad-private/redis-cache
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: ~

port: 5000
targetPort: 5000
namespace: devnet

logPath: /app/logs

replicas:
  publicApi: 1

env:
  REDIS_URL: redis://cache
  NODE_ENV: development
  PORT: 3000

resources:
  limits:
    cpu: 0.2
    memory: 128M 
  requests:
    cpu: 0.2
    memory: 128M 
